[tool.poetry]
name = "crypto-virality-e2e-model"
version = "0.1.0"
description = ""
authors = ["Haydn Martin"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
jupyter = "^1.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"


